
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '}!\xab\xe9\x90\xf0\x9bu\xd8"\x1fn\xb8\x9d\xbeY'
    
_lr_action_items = {'REPITA':([0,],[1,]),'CIMA':([0,12,13,23,26,33,34,35,36,37,38,39,41,],[2,27,27,-9,27,-14,-11,-12,-15,-10,-16,-13,27,]),'VERDADEIRO':([10,21,],[15,15,]),'ENQUANTO':([0,],[3,]),'SENSORDIREITA':([10,21,],[17,17,]),'VEZES':([9,],[13,]),'FALSO':([10,21,],[18,18,]),'FACA':([11,23,33,34,35,36,37,38,39,],[26,-9,-14,-11,-12,-15,-10,-16,-13,]),'NUMERO':([1,],[9,]),'BAIXO':([0,12,13,23,26,33,34,35,36,37,38,39,41,],[4,28,28,-9,28,-14,-11,-12,-15,-10,-16,-13,28,]),'COLUNAESQUERDA':([3,8,],[10,10,]),'SENAO':([27,28,29,30,31,],[-22,-24,41,-23,-21,]),'COLUNADIREITA':([14,15,16,17,18,19,20,22,24,25,],[33,34,-18,-19,35,-17,36,38,-20,39,]),'ESQUERDA':([0,12,13,23,26,33,34,35,36,37,38,39,41,],[6,30,30,-9,30,-14,-11,-12,-15,-10,-16,-13,30,]),'SENSORESQUERDA':([10,21,],[16,16,]),'NEGACAO':([10,],[21,]),'SENSORBAIXO':([10,21,],[24,24,]),'SENSORCIMA':([10,21,],[19,19,]),'DIREITA':([0,12,13,23,26,33,34,35,36,37,38,39,41,],[5,31,31,-9,31,-14,-11,-12,-15,-10,-16,-13,31,]),'SE':([0,],[8,]),'$end':([2,4,5,6,7,27,28,29,30,31,32,40,42,],[-1,-4,-2,-3,0,-22,-24,-5,-23,-21,-8,-7,-6,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'sensorDireita':([10,21,],[14,14,]),'blocoLogico':([3,8,],[11,12,]),'blocoExecutar':([12,13,26,41,],[29,32,40,42,]),'sensorEsquerda':([10,21,],[20,20,]),'sensorBaixo':([10,21,],[22,22,]),'assign':([0,],[7,]),'sensorCima':([10,21,],[25,25,]),'logico':([10,21,],[23,37,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> assign","S'",1,None,None,None),
  ('assign -> CIMA','assign',1,'p_assign_mover_frente','D:\\Documents\\GitHub\\Raspython\\model\\Interpretador\\AnalisadorSintatico.py',13),
  ('assign -> DIREITA','assign',1,'p_assign_mover_direita','D:\\Documents\\GitHub\\Raspython\\model\\Interpretador\\AnalisadorSintatico.py',17),
  ('assign -> ESQUERDA','assign',1,'p_assign_mover_esquerda','D:\\Documents\\GitHub\\Raspython\\model\\Interpretador\\AnalisadorSintatico.py',21),
  ('assign -> BAIXO','assign',1,'p_assign_mover_volta','D:\\Documents\\GitHub\\Raspython\\model\\Interpretador\\AnalisadorSintatico.py',25),
  ('assign -> SE blocoLogico blocoExecutar','assign',3,'p_se_stmt','D:\\Documents\\GitHub\\Raspython\\model\\Interpretador\\AnalisadorSintatico.py',29),
  ('assign -> SE blocoLogico blocoExecutar SENAO blocoExecutar','assign',5,'p_se_senao_stmt','D:\\Documents\\GitHub\\Raspython\\model\\Interpretador\\AnalisadorSintatico.py',34),
  ('assign -> ENQUANTO blocoLogico FACA blocoExecutar','assign',4,'p_enquanto_stmt','D:\\Documents\\GitHub\\Raspython\\model\\Interpretador\\AnalisadorSintatico.py',41),
  ('assign -> REPITA NUMERO VEZES blocoExecutar','assign',4,'p_faca_stmt','D:\\Documents\\GitHub\\Raspython\\model\\Interpretador\\AnalisadorSintatico.py',47),
  ('blocoLogico -> COLUNAESQUERDA logico','blocoLogico',2,'p_blocoLogico','D:\\Documents\\GitHub\\Raspython\\model\\Interpretador\\AnalisadorSintatico.py',54),
  ('blocoLogico -> COLUNAESQUERDA NEGACAO logico','blocoLogico',3,'p_blocoLogico','D:\\Documents\\GitHub\\Raspython\\model\\Interpretador\\AnalisadorSintatico.py',55),
  ('logico -> VERDADEIRO COLUNADIREITA','logico',2,'p_logico','D:\\Documents\\GitHub\\Raspython\\model\\Interpretador\\AnalisadorSintatico.py',63),
  ('logico -> FALSO COLUNADIREITA','logico',2,'p_logico','D:\\Documents\\GitHub\\Raspython\\model\\Interpretador\\AnalisadorSintatico.py',64),
  ('logico -> sensorCima COLUNADIREITA','logico',2,'p_logico','D:\\Documents\\GitHub\\Raspython\\model\\Interpretador\\AnalisadorSintatico.py',65),
  ('logico -> sensorDireita COLUNADIREITA','logico',2,'p_logico','D:\\Documents\\GitHub\\Raspython\\model\\Interpretador\\AnalisadorSintatico.py',66),
  ('logico -> sensorEsquerda COLUNADIREITA','logico',2,'p_logico','D:\\Documents\\GitHub\\Raspython\\model\\Interpretador\\AnalisadorSintatico.py',67),
  ('logico -> sensorBaixo COLUNADIREITA','logico',2,'p_logico','D:\\Documents\\GitHub\\Raspython\\model\\Interpretador\\AnalisadorSintatico.py',68),
  ('sensorCima -> SENSORCIMA','sensorCima',1,'p_sensorCima','D:\\Documents\\GitHub\\Raspython\\model\\Interpretador\\AnalisadorSintatico.py',76),
  ('sensorEsquerda -> SENSORESQUERDA','sensorEsquerda',1,'p_sensorEsquerda','D:\\Documents\\GitHub\\Raspython\\model\\Interpretador\\AnalisadorSintatico.py',81),
  ('sensorDireita -> SENSORDIREITA','sensorDireita',1,'p_sensorDireita','D:\\Documents\\GitHub\\Raspython\\model\\Interpretador\\AnalisadorSintatico.py',86),
  ('sensorBaixo -> SENSORBAIXO','sensorBaixo',1,'p_sensorBaixo','D:\\Documents\\GitHub\\Raspython\\model\\Interpretador\\AnalisadorSintatico.py',91),
  ('blocoExecutar -> DIREITA','blocoExecutar',1,'p_blocoExecutar','D:\\Documents\\GitHub\\Raspython\\model\\Interpretador\\AnalisadorSintatico.py',97),
  ('blocoExecutar -> CIMA','blocoExecutar',1,'p_blocoExecutar','D:\\Documents\\GitHub\\Raspython\\model\\Interpretador\\AnalisadorSintatico.py',98),
  ('blocoExecutar -> ESQUERDA','blocoExecutar',1,'p_blocoExecutar','D:\\Documents\\GitHub\\Raspython\\model\\Interpretador\\AnalisadorSintatico.py',99),
  ('blocoExecutar -> BAIXO','blocoExecutar',1,'p_blocoExecutar','D:\\Documents\\GitHub\\Raspython\\model\\Interpretador\\AnalisadorSintatico.py',100),
]
