
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\xe6\xa1\x9c\xbf\x08\x01\x93n\x9e\xfd%\\\xdc\xb3i\x02'
    
_lr_action_items = {'REPITA':([0,],[1,]),'CIMA':([0,12,13,14,25,26,27,28,],[2,18,18,18,-11,-9,-10,18,]),'VERDADEIRO':([11,],[16,]),'ENQUANTO':([0,],[3,]),'SENAO':([18,19,20,21,22,],[-13,-15,28,-14,-12,]),'VEZES':([9,],[13,]),'FALSO':([11,],[17,]),'FACA':([10,25,26,27,],[14,-11,-9,-10,]),'NUMERO':([1,],[9,]),'BAIXO':([0,12,13,14,25,26,27,28,],[4,19,19,19,-11,-9,-10,19,]),'COLUNAESQUERDA':([3,8,],[11,11,]),'SENSORFRENTE':([11,],[15,]),'ESQUERDA':([0,12,13,14,25,26,27,28,],[6,21,21,21,-11,-9,-10,21,]),'COLUNADIREITA':([15,16,17,],[25,26,27,]),'DIREITA':([0,12,13,14,25,26,27,28,],[5,22,22,22,-11,-9,-10,22,]),'SE':([0,],[8,]),'$end':([2,4,5,6,7,18,19,20,21,22,23,24,29,],[-1,-4,-2,-3,0,-13,-15,-5,-14,-12,-8,-7,-6,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expressao':([3,8,],[10,12,]),'blocoExecutar':([12,13,14,28,],[20,23,24,29,]),'assign':([0,],[7,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> assign","S'",1,None,None,None),
  ('assign -> CIMA','assign',1,'p_assign_mover_frente','D:\\Documents\\GitHub\\Raspython\\model\\Interpretador\\AnalisadorSintatico.py',13),
  ('assign -> DIREITA','assign',1,'p_assign_mover_direita','D:\\Documents\\GitHub\\Raspython\\model\\Interpretador\\AnalisadorSintatico.py',17),
  ('assign -> ESQUERDA','assign',1,'p_assign_mover_esquerda','D:\\Documents\\GitHub\\Raspython\\model\\Interpretador\\AnalisadorSintatico.py',21),
  ('assign -> BAIXO','assign',1,'p_assign_mover_volta','D:\\Documents\\GitHub\\Raspython\\model\\Interpretador\\AnalisadorSintatico.py',25),
  ('assign -> SE expressao blocoExecutar','assign',3,'p_se_stmt','D:\\Documents\\GitHub\\Raspython\\model\\Interpretador\\AnalisadorSintatico.py',29),
  ('assign -> SE expressao blocoExecutar SENAO blocoExecutar','assign',5,'p_se_senao_stmt','D:\\Documents\\GitHub\\Raspython\\model\\Interpretador\\AnalisadorSintatico.py',34),
  ('assign -> ENQUANTO expressao FACA blocoExecutar','assign',4,'p_enquanto_stmt','D:\\Documents\\GitHub\\Raspython\\model\\Interpretador\\AnalisadorSintatico.py',41),
  ('assign -> REPITA NUMERO VEZES blocoExecutar','assign',4,'p_faca_stmt','D:\\Documents\\GitHub\\Raspython\\model\\Interpretador\\AnalisadorSintatico.py',47),
  ('expressao -> COLUNAESQUERDA VERDADEIRO COLUNADIREITA','expressao',3,'p_expressao','D:\\Documents\\GitHub\\Raspython\\model\\Interpretador\\AnalisadorSintatico.py',54),
  ('expressao -> COLUNAESQUERDA FALSO COLUNADIREITA','expressao',3,'p_expressao','D:\\Documents\\GitHub\\Raspython\\model\\Interpretador\\AnalisadorSintatico.py',55),
  ('expressao -> COLUNAESQUERDA SENSORFRENTE COLUNADIREITA','expressao',3,'p_expressao','D:\\Documents\\GitHub\\Raspython\\model\\Interpretador\\AnalisadorSintatico.py',56),
  ('blocoExecutar -> DIREITA','blocoExecutar',1,'p_blocoExecutar','D:\\Documents\\GitHub\\Raspython\\model\\Interpretador\\AnalisadorSintatico.py',63),
  ('blocoExecutar -> CIMA','blocoExecutar',1,'p_blocoExecutar','D:\\Documents\\GitHub\\Raspython\\model\\Interpretador\\AnalisadorSintatico.py',64),
  ('blocoExecutar -> ESQUERDA','blocoExecutar',1,'p_blocoExecutar','D:\\Documents\\GitHub\\Raspython\\model\\Interpretador\\AnalisadorSintatico.py',65),
  ('blocoExecutar -> BAIXO','blocoExecutar',1,'p_blocoExecutar','D:\\Documents\\GitHub\\Raspython\\model\\Interpretador\\AnalisadorSintatico.py',66),
]
